'use strict';
const products=window.RUNEC_PRODUCTS||[], labels=window.RUNEC_LABELS||[]; let current=null,selectedLabel='';
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function buildTree(list){const groups={};list.forEach(p=>(groups[p.category]??=[]).push(p));$('categoryTree').innerHTML=Object.entries(groups).map(([g,ps])=>`<div class="group"><div class="group-name">📂 ${esc(g)}</div>${ps.map(p=>`<button class="tree-product" data-id="${esc(p.id)}">🔧 ${esc(p.id)}－${esc(p.name)}</button>`).join('')}</div>`).join('');document.querySelectorAll('.tree-product').forEach(b=>b.onclick=()=>selectProduct(products.find(p=>p.id===b.dataset.id)));}
function selectProduct(p){if(!p)return;current=p;document.querySelectorAll('.tree-product').forEach(x=>x.classList.toggle('active',x.dataset.id===p.id));$('crumbCategory').textContent=p.category;$('crumbId').textContent=p.id;['id','name','memo','internalMemo','reference','unit','substitute','startDate','endDate','itemClass','status','updatedAt'].forEach(k=>$(k).value=p[k]??'');$('stockable').checked=!!p.stockable;$('taxable').checked=!!p.taxable;$('pinned').checked=!!p.pinned;$('productPhoto').src=p.photo;renderRows('partnerRows',p.partners,['partner','code','name','memo','level']);renderRows('safeRows',p.safeStocks,['warehouse','low','high']);renderRows('stockRows',p.stocks,['warehouse','qty']);renderRows('attachmentRows',p.attachments,['content','memo']);renderLabels();refreshPreview();}
function renderRows(id,rows,keys){$(id).innerHTML=rows.length?rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${keys.length}" class="empty">尚無資料</td></tr>`;}
function matchedLabels(){const q=($('labelSearch').value||'').trim().toLowerCase();const tokens=current?current.id.toLowerCase().split(/[-\s()]+/).filter(x=>x.length>=3):[];return labels.filter(l=>{const n=l.name.toLowerCase();const relevant=tokens.some(t=>n.includes(t))||n.includes((current?.id||'').toLowerCase());return (!q||n.includes(q))&&(relevant||!q);});}
function renderLabels(){const list=matchedLabels();$('labelCount').textContent=`${list.length} 個模板`;$('labelPool').innerHTML=list.length?list.map(l=>`<div class="label-card ${selectedLabel===l.name?'selected':''}"><b>${esc(l.name)}</b><small>${esc(l.category)}</small><div><button data-pick="${esc(l.name)}">選用</button> <a href="${encodeURI(l.file)}" download>下載 EZP</a></div></div>`).join(''):'<div class="empty">此商品尚未找到相符標籤；可輸入關鍵字搜尋全部模板。</div>';document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{selectedLabel=b.dataset.pick;renderLabels();});}
function refreshPreview(){if(!current)return;$('pProductNo').textContent=current.id;$('pName').textContent=current.name;$('pMemo').textContent=selectedLabel||current.internalMemo||current.memo;$('pBatch').textContent=`批號：${$('batchNo').value||'-'}　份數：${$('printQty').value||1}`;}
function search(){const q=$('searchInput').value.trim().toLowerCase();const hits=products.filter(p=>`${p.id} ${p.name} ${p.category}`.toLowerCase().includes(q));buildTree(hits);if(hits[0])selectProduct(hits[0]);}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active');});
$('searchBtn').onclick=search;$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search();});$('labelSearch').addEventListener('input',renderLabels);$('batchNo').addEventListener('input',refreshPreview);$('printQty').addEventListener('input',refreshPreview);$('printBtn').onclick=()=>window.print();
buildTree(products);selectProduct(products[0]);
