-- Auto generated by 17upload_ads_media_to_r2_universal.py
-- 更新首頁 index.html 會讀的 Supabase assets.cover_url
-- topic = wealth-power

update public.assets
set cover_url = 'https://pub-578e9e060a104f24b6865e26eb941648.r2.dev/ads/monk/wealth-power/monk_wealth_power01.png',
    source_url = '/heart.html?topic=wealth-power',
    is_published = true,
    review_status = 'approved',
    updated_at = now()
where category = 'monk'
  and slug = 'wealth-power';

-- 檢查
select category, slug, title, difficulty_level, is_published, review_status, cover_url, source_url
from public.assets
where category = 'monk'
  and slug = 'wealth-power';
